[package]
edition = "2021"
name = "alignment"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jean = {version = "0.1.0", path = "../../lib/jean", features = ["alignment", "macros"]}
